LionStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import mainApp.views

import account.urls
import mainApp.urls

urlpatterns = [
    path('', mainApp.views.intro_view, name='introPage'),
    path('admin/', admin.site.urls),
    path('account/', include(account.urls)),
    path('store/', include(mainApp.urls)),
    path('randomLike/', mainApp.views.randomLike, name="randomLike"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path

from . import views

# /account/...
urlpatterns = [
    # 마이 페이지
    path('myPage/', views.myPage_view, name='myPage'),
    path('myPageRedirector/<target>', views.myPageRedirector, name="myPageRedirector"),

    # 로그인 / 로그아웃 / 회원가입 관련
    path('logIn/', views.login_view, name='logIn'),
    path('logOut/', views.logout_view, name='logOut'),
    path('signUp/', views.selectCustomerType_view, name='selectCustomerType'),
    path('signUp/sellerType/', views.selectSellerType_view, name='selectSellerType'),
    path('signUp/user/', views.userSignUp_view, name='userSignUp'),
    path('signUp/webSeller/', views.webSellerSignUp_view, name='webSellerSignUp'),
    path('signUp/stationer/', views.stationerSignUp_view, name='stationerSignUp'),
    path('setLocation/', views.setLocation_view, name="setLocation"),

    # 계정 정보 수정 관련
    path('modifyUserInfo/', views.modifyUserInfo_view, name='modifyUserInfo'),

    # 작성한 웹 판매 정보 목록
    path('webSellInfoList/', views.webSellerInfoList_view, name='webSellInfoList'),
    # 작성한 문구점 판매 정보 목록
    path('stationerSellInfoList/', views.stationerSellInfoList_view, name='stationerSellInfoList'),
]

mainApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from . import tools

# /store/...
urlpatterns = [
    # 프로젝트 메인 페이지
    path('main/', views.mainPage_view, name="mainPage"),

    # 제품 등록 요청 관련
    path('productRequest/', views.productRequest_view, name="productRequestList"),
    path('productRequest/create', views.newProductRequest_view,
         name="newProductRequest"),
    path('productRequest/<int:product_request_id>', views.productRequestDetail_view, name="productRequestDetail"),
    path('productRequest/modify/<int:product_request_id>', views.productRequestModify_view, name="productRequestModify"),
    path('productRequest/delete/<int:product_request_id>', views.productRequestDelete_view, name="productRequestDelete"),

    # 카테고리별 제품 목록
    path('productList/<int:category_id>', views.productList_view, name="productList"),
    # 제품 상세 정보
    path('productDetail/<int:product_id>', views.productDetail_view, name="productDetail"),

    # 제품 좋아요 관련
    path('productLikeProcess/<int:product_id>',
         views.productLikeProcess, name="productLikeProcess"),
    path('productLike/<int:product_id>', views.productLike, name="productLike"),
    path('productDislike/<int:product_id>', views.productDislike, name="productDislike"),

    # 리뷰 관련
    path('productList/<int:product_id>/newReview', views.reviewCreate_view, name="reviewCreate"),
    path('reviewDetail/<int:review_id>', views.reviewDetail_view, name="reviewDetail"),
    path('reviewModify/<int:review_id>', views.reviewModify_view, name="reviewModify"),
    path('reviewUpdate/<int:review_id>', views.reviewUpdate, name="reviewUpdate"),
    path('reviewDelete/<int:review_id>', views.reviewDelete, name="reviewDelete"),
    path('reviewImageModify/<int:review_id>/<path:imageURL>', views.reviewImageModify_view, name="reviewImageModify"),
    path('reviewImageDelete/<int:review_id>/<path:imageURL>', views.reviewImageDelete, name="reviewImageDelete"),
    path('reviewImageAdd/<int:review_id>', views.reviewImageAdd, name="reviewImageAdd"),
     path('firstReviewImageModify/<int:review_id>', views.firstReviewImageModify_view, name="firstReviewImageModify"),
     path('firstReviewImageDelete/<int:review_id>', views.firstReviewImageDelete, name="firstReviewImageDelete"),

     # 댓글 관련
     path('commentCreate/<int:review_id>', views.commentCreate, name="commentCreate"),
     path('commentDelete/<int:comment_id>', views.commentDelete, name="commentDelete"),

    # 리뷰 좋아요
    path('reviewLikeProcess/<int:review_id>',
         views.reviewLikeProcess, name="reviewLikeProcess"),
    path('reviewLike/<int:review_id>', views.reviewLike, name="reviewLike"),
    path('reviewDislike/<int:review_id>', views.reviewDislike, name="reviewDislike"),

    # 웹 판매정보 관련
    path('productList/<int:product_id>/newWebSellInfo', views.webSellInfoCreate_view, name="webSellInfoCreate"),
    path('productList/<int:product_id>/webSellInfoModify/<int:webSellInfo_id>', views.webSellInfoModify_view, name="webSellInfoModify"),
    path('productList/<int:product_id>/webSellInfoDelete/<int:webSellInfo_id>', views.webSellInfoDelete, name="webSellInfoDelete"),

    # 문구점 판매정보 관련
    path('productList/<int:product_id>/newStationerSellInfo', views.stationerSellInfoCreate_view, name="stationerSellInfoCreate"),
    path('productList/<int:product_id>/stationerSellInfoModify/<int:stationerSellInfo_id>', views.stationerSellInfoModify_view, name="stationerSellInfoModify"),
    path('productList/<int:product_id>/stationerSellInfoDelete/<int:stationerSellInfo_id>', views.stationerSellInfoDelete, name="stationerSellInfoDelete"),

    # 검색 관련
    path('searchMain', views.searchMain_view, name="searchMain"),
    path('keywordSearchResult', views.keywordSearchResult_view, name="keywordSearchResult"),
    path('tagSearchResult', views.tagSearchResult_view, name="tagSearchResult"),
    
    # 추천
    path('userRecommendation', views.userRecommendation_view, name="userRecommendation"),

    # 특정 태그가 달려있는 제품의 목록
    path('tagProduct/<int:productTag_id>', views.tagProduct_view, name="tagProduct"),
    # 특정 태그를 가지는 사람들의 리뷰 목록
    path('reviewsByTag/<str:tagName>', views.reviewsByTag_view, name="reviewsByTag"),

    # 외부 링크로 리다이렉트 하기 위한 url
    path('redirectExternalLink/<path:link>', tools.redirectExternalLink, name='redirectExternalLink'),

     # 카테고리 이름으로 productList에 Redirect
     path('redirectByCategoryName/<categoryName>', tools.redirectByCategoryName, name="redirectByCategoryName"),
]

mainApp/models.py
import os, sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from account.models import Customer

# 제품
class Product(models.Model):
    class Meta:
        verbose_name = "제품"

    name = models.CharField(max_length=30, verbose_name="상품 이름")
    manufacturer = models.CharField(max_length=30, verbose_name="제조사")
    description = models.TextField(verbose_name="상품 설명")
    registerDate = models.DateTimeField(auto_now_add=True, verbose_name="등록일")
    category = models.ForeignKey('ProductCategory', null=False, blank=False, on_delete=models.CASCADE, related_name="productCategory", verbose_name="소속 카테고리")
    likers = models.ManyToManyField(Customer, blank=True, related_name='productLikers', verbose_name="좋아요")
    likeCount = models.PositiveIntegerField(default=0, verbose_name='좋아요 수')
    productImage = models.ImageField(upload_to="product_image/", null=False, verbose_name="상품 이미지")

    def __str__(self):
        return f"{self.manufacturer}) {self.name}"

    def averageScore(self):
        reviews = PenReview.objects.filter(product=self)
        if len(reviews) == 0:
            return 0
        else:
            return sum(list(map(lambda r: r.totalScore, reviews))) / len(reviews)

    def getShortDescription(self):
        return self.description if len(self.description) < 20 else self.description[:17] + "..."


# 제품 관련 영상 링크
class ProductVideoLink(models.Model):
    class Meta:
        verbose_name = "상품 관련 유튜브 영상 링크"

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False, related_name='linkTargetProduct', verbose_name="대상 상품")
    videoLink = models.CharField(max_length=100, verbose_name="유튜브 링크")

# 제품 카테고리
class ProductCategory(models.Model):
    class Meta:
        verbose_name = "제품 카테고리"

    categoryName = models.CharField(max_length=15, verbose_name="카테고리 이름")

    def __str__(self):
        return f"{self.id}. {self.categoryName}"

# 웹 판매 정보
class WebSellInfo(models.Model):
    class Meta:
        verbose_name = "웹 판매 정보"

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False, related_name='webSellInfoTargetProduct', verbose_name="대상 상품")
    seller = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, related_name='webSellInfoSeller', verbose_name="웹 판매자")
    link = models.CharField(max_length=300, null=False, blank=False, verbose_name="판매정보 링크")
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name="판매가")
    reported = models.BooleanField(default=False, verbose_name="신고")

    def __str__(self):
        reported = "🚨" if self.reported else ""
        return f"{reported} 판매자 : {self.seller.nickname}"

# 문방구 판매 정보
class StationerSellInfo(models.Model):
    class Meta:
        verbose_name = "문방구 판매 정보"

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False, related_name='StationerSellInfoTargetProduct', verbose_name="대상 상품")
    seller = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, related_name='StationerSellInfoSeller', verbose_name="문방구 판매자")
    price = models.PositiveIntegerField(verbose_name="판매가")
    reported = models.BooleanField(default=False, verbose_name="신고")

# 리뷰
class Review(models.Model):
    class Meta:
        verbose_name = "제품 리뷰"

    author = models.ForeignKey("account.Customer", on_delete=models.CASCADE, null=True, related_name='reviewAuthor', verbose_name="리뷰 작성자")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, related_name='reviewTargetProduct', verbose_name="대상 상품")
    pub_date = models.DateTimeField(null=True, blank=True, verbose_name="리뷰 작성일")
    totalScore = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=False, verbose_name="총점")
    comment = models.CharField(max_length=50, default="", null=False, blank=False, verbose_name="한줄평")
    goodPoint = models.TextField(verbose_name="장점")
    weakPoint = models.TextField(verbose_name="단점")
    likers = models.ManyToManyField(Customer, related_name='reviewLikers', verbose_name="좋아요")
    likeCount = models.PositiveIntegerField(default=0, verbose_name='좋아요 수')

    reported = models.BooleanField(default=False, verbose_name="신고")
    modified = models.BooleanField(default=False, verbose_name="수정")

    reviewImage1 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지1")
    reviewImage2 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지2")
    reviewImage3 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지3")
    reviewImage4 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지4")
    reviewImage5 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지5")
    reviewImage6 = models.ImageField(upload_to="review_image/", blank=True, null=True, verbose_name="리뷰 이미지6")

    tags = models.ManyToManyField('ReviewTag', blank=True)
    rawTagString = models.TextField(null=False, blank=True, default="", verbose_name="제품 태그 목록 원본 데이터")

    def getRoundTotalScore(self):
        strScore = str(self.totalScore)
        tokens = strScore.split('.')
        return f"{tokens[0]}.{tokens[1][:1]}"

    def getShortComment(self):
        return self.comment if len(self.comment) < 20 else self.comment[:17] + "..."

    def getMainImage(self):
        firstImage = self.reviewImage1
        
        images = [self.reviewImage2, self.reviewImage3, self.reviewImage4, self.reviewImage5, self.reviewImage6]
        for image in images:
            if image:
                firstImage = image
                break

        return firstImage

# 점수
class Score(models.Model):
    class Meta:
        verbose_name = "제품 별점"

    review = models.ForeignKey(Review, on_delete=models.CASCADE, blank=False, null=True, related_name="scoreTargetReview", verbose_name="대상 리뷰")
    name = models.CharField(max_length=20, verbose_name="평가 항목")
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=1, verbose_name="평가 점수")

    def __str__(self):
        return self.name + " : " + str(self.score) + "점"

# 펜 리뷰
class PenReview(Review):
    class Meta:
        verbose_name = "펜 리뷰"

    grip = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='grip', verbose_name="그립감")
    life = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='life', verbose_name="제품 수명")
    durability = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='durability', verbose_name="내구도")
    design = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='design', verbose_name="디자인")
    texture = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='texture', verbose_name="사용감")
    costEffetiveness = models.ForeignKey(Score, on_delete=models.CASCADE, blank=False, null=True, related_name='costEffetiveness', verbose_name="가성비")

    def __str__(self):
            description = self.comment if len(self.comment) <= 10 else (self.comment[:10] + "...")
            return f"{self.product.name}) {description}"

# 상품의 특성
class ReviewTag(models.Model):
    class Meta:
        verbose_name = "리뷰 태그"

    targetReview = models.ManyToManyField('Review', blank=True, verbose_name="가리키는 상품")
    tag = models.CharField(max_length=15, verbose_name="상품 태그")

    def __str__(self):
        return self.tag

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name="commentTargetReview", verbose_name="대상 리뷰")
    author = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='commentAuthor', verbose_name="리뷰 작성자")
    pub_date = models.DateTimeField(verbose_name="리뷰 작성(수정)일")
    body = models.TextField(verbose_name="댓글 내용")

    def __str__(self):
        return f"{self.body[:10]}.. (by {self.author.nickname}, on {self.pub_date}" 


# 상품 등록 요청
class ProductRequest(models.Model):
    class Meta:
        verbose_name = "상품 등록 요청"
    
    author = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="productRequestAuthor", verbose_name="제품 등록 요청자")
    productName = models.CharField(max_length=20, null=False, blank=False, verbose_name="제품 이름")
    productBrand = models.CharField(max_length=20, null=True, blank=True, verbose_name="제품 브랜드")
    productDescription = models.TextField(null=True, blank=True, verbose_name="제품 설명")
    isChecked = models.BooleanField(default=False, verbose_name="확인여부")

    def __str__(self):
        return self.productName

    def getShortDescription(self):
        return self.productDescription if len(self.productDescription) < 50 else self.productDescription[:57] + "..."

mainApp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db import transaction

from .models import PenReview
from .models import ProductRequest
from .models import WebSellInfo, StationerSellInfo

from .widgets import starWidget

class PenReviewForm(forms.ModelForm):
    class Meta:
        model = PenReview
        fields = ['goodPoint', 'weakPoint', 'rawTagString',
        'reviewImage1', 'reviewImage2', 'reviewImage3', 'reviewImage4', 'reviewImage5', 'reviewImage6',]

class ReviewImageModifyingForm(forms.ModelForm):
    class Meta:
        model = PenReview
        fields = ['reviewImage1']

class ReviewImageAddForm(forms.ModelForm):
    class Meta:
        model = PenReview
        fields = ['reviewImage1']

class NewProductRequestForm(forms.ModelForm):
    class Meta:
        model = ProductRequest
        fields = ['productName', 'productBrand', 'productDescription',]

class WebSellInfoForm(forms.ModelForm):
    class Meta:
        model = WebSellInfo
        fields = ['link', 'price']


class StationerSellInfoForm(forms.ModelForm):
    class Meta:
        model = StationerSellInfo
        fields = ['price']

mainApp/templates/firstReviewImageModify.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>리뷰 이미지 수정</title>
<!-- 리뷰 이미지 수정 페이지  -->
{% endblock %}

{% block content %}

<div>현재 이미지</div>
<img src="{{ image.url }}" style="width: 20rem; height: 20rem;">

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.reviewImage1 }}
    <br>
    <input type="submit" value="수정 완료">
</form>
<a href="{% url 'firstReviewImageDelete' review.id %}"><button>이미지 삭제</button></a>
<a href="{% url 'reviewDetail' review.id %}"><button>취소</button></a>

{% endblock %}

mainApp/templates/introPage.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>인트로 페이지</title>
{% endblock %}

{% block content %}
<div>인트로 페이지입니다.</div>
{% if not user.is_authenticated %}
<a href="{% url 'selectCustomerType' %}"><button>회원가입</button></a>
{% endif %}
<a href="{% url 'mainPage' %}"><button>HOME</button></a>
{% endblock %}

mainApp/templates/keywordSearchResult.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>제품 검색 결과</title>
<!-- 제품 검색 결과 리스트가 노출되며, Pagination을 사용할 경우 url이 살짝 달라질 수도 있다.
     각 제품 목록 구성 요소를 클릭하면 productDetail.html로 넘어간다. -->
{% endblock %}

{% block content %}

<h4 style="text-align: center; padding: 1em 3rem 0 3rem; font-family: 'yg-jalnan'; color:#663e27;"><i class="fa fa-edit"></i>
     {{ statusMessage }}</h4><br>
<br><br><br>

<article style="margin: 0 2rem;">
     <!-- 인기순 정렬로 전환 -->
     {% if popularitySort %}
     <div style="text-align: left; font-family: 'yg-jalnan'; padding-left: 0.3rem;"><i class="fa fa-sort" aria-hidden="true"></i><span>인기순 정렬</span> / <span><a href="{% url 'keywordSearchResult' %}?sort=new&keywordQuery={{ keywordQuery }}">최신순정렬</a></span></div>
     <!-- 최신순 정렬로 전환 -->
     {% else %}
     <div style="text-align: left; font-family: 'yg-jalnan'; padding-left: 0.3rem;"><i class="fa fa-sort" aria-hidden="true"></i><span><a href="{% url 'keywordSearchResult' %}?sort=popularity&keywordQuery={{ keywordQuery }}">인기순 정렬</a></span> / <span>최신순정렬</span></div>
     {% endif %}

     <div class="reviewContainer">
<div class="row property__gallery">
     {% for product in searchResult %}
     <div class="col-lg-3 col-md-4 col-sm-6 mix women">
          <div class="product__item">
               <div class="product__item__pic set-bg" data-setbg="{{ product.productImage.url }}">
                    <ul class="product__hover">
                         <li><a href="{{ product.productImage.url }}" class="image-popup"><span
                                        class="arrow_expand"></span></a></li>
                    </ul>
               </div>
               <div class="product__item__text">
                    <div><a href="{% url 'productDetail' product.id %}">{{ product }}</a></div>                    <div class="rating">
                         <div class="rateit svg" data-rateit-value="{{ product.averageScore }}"
                              data-rateit-readonly="true" data-rateit-starwidth="15" data-rateit-starheight="15">
                         </div>
                    </div>
               </div>
          </div>
     </div>
     {% endfor %}
</div>
</div>
</article>


{% endblock %}

mainApp/templates/reviewModify.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>리뷰 수정</title>
<!-- 리뷰의 내용을 수정함 -->
<style>
    #mainContainer {
         width: 80%;
         text-align: center;
         margin: 2rem auto;
    }
    #product_image {
         display: block;
         max-width: 700px;
         max-height: 550px;
         width: auto;
         height: auto;
    }
    #no_review_message {
         text-align: center;
    }
    #no_review_message div {
         font-family: 'yg-jalnan';
         color:#663e27;
    }
    iframe {
         display:block; 
         width:70vw; 
         height: 80vh
    }
    @font-face {
       font-family: 'yg-jalnan';
       src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');
       font-weight: normal;
       font-style: normal;
   }

   @font-face {
       font-family: 'NanumSquareRound';
       src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/NanumSquareRound.woff') format('woff');
       font-weight: normal;
       font-style: normal;
   }

   textarea.noresize {
       border: 1.5px solid #66666644; 
       width: 100%; 
       height: 140px;
       border-radius: 7px; 
       resize: none
   }

   textarea.tag {
       border: 1.5px solid #66666644; 
       width: 100%; 
       height: 80px;
       border-radius: 7px; 
       resize: none
   }

</style>
{% endblock %}

{% block content %}
<div id="mainContainer container" style="width: 80%; margin: 2rem auto; padding: 2rem 5%;">
    <div class="product_detail col container">
        <div class="product_detail row" style="text-align: left; display: grid; grid-template-rows: 1fr 0.4fr; width: 100%;">
            <p class="h2" style="text-align: left; font-family: 'yg-jalnan'; color: hsl(32, 81%, 44%);">리뷰 수정하기</p>
            <div class="footer__newslatter_2" style="text-align: left; width: 100%;">
                <form action="{% url 'reviewUpdate' review.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p class="h5" style="text-align: left; font-family: 'yg-jalnan';">한줄평</p>
                    <input type="text" name="comment" id="comment" value="{{ review.comment }}">
                </form>
            </div>
        </div>  
    </div>
    <hr>
    <div class="product_detail col container">
        <div class="scoreContainer" style="margin-top: 1.5rem;">
            <div class="row">
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">그립감</div>
                    <input type="rating" name="grip" value="{{ review.grip.score }}" required="" id="id_grip" min="0" max="5" step="1" style="display: none;">
                    <div id="star_id_grade" class="rateit svg" data-rateit-backingfld="#id_grip" data-rateit-starwidth="15"
                        data-rateit-starheight="15"></div>
                </div>
            <br>
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">수명</div>
                    <input type="rating" name="life" value="{{ review.life.score }}" required="" id="id_life" min="0" max="5" step="1" style="display: none;">
                    <div id="star_id_life" class="rateit svg" data-rateit-backingfld="#id_life" data-rateit-starwidth="15"
                       data-rateit-starheight="15"></div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">내구도</div>
                    <input type="rating" name="durability" value="{{ review.durability.score }}" required="" id="id_durability" min="0" max="5" step="1"
                        style="display: none;">
                    <div id="star_id_durability" class="rateit svg" data-rateit-backingfld="#id_durability" data-rateit-starwidth="15"
                        data-rateit-starheight="15"></div>
                </div>
            <br>
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">디자인</div>
                    <input type="rating" name="design" value="{{ review.design.score }}" required="" id="id_design" min="0" max="5" step="1"
                        style="display: none;">
                    <div id="star_id_design" class="rateit svg" data-rateit-backingfld="#id_design" data-rateit-starwidth="15"
                        data-rateit-starheight="15"></div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">사용감</div>
                    <input type="rating" name="texture" value="{{ review.texture.score }}" required="" id="id_texture" min="0" max="5" step="1"
                        style="display: none;">
                    <div id="star_id_texture" class="rateit svg" data-rateit-backingfld="#id_texture" data-rateit-starwidth="15"
                        data-rateit-starheight="15"></div>
                </div>
            <br>
                <div class="col">
                    <div class="h6" style="font-family: 'yg-jalnan'; font-weight: bold;">가성비</div>
                    <input type="rating" name="costEffetiveness" value="{{ review.costEffetiveness.score }}" required="" id="id_costEffetiveness" min="0" max="5" step="1"
                        style="display: none;">
                    <div id="star_id_costEffetiveness" class="rateit svg" data-rateit-backingfld="#id_costEffetiveness"
                        data-rateit-starwidth="15" data-rateit-starheight="15"></div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="product_detail col container">
        <div class="product_detail row" style="text-align: left; display: grid; grid-template-rows: 1fr 1.5fr;">
            <br>
            <p class="h5" style="text-align: left; font-family: 'yg-jalnan';">장점</p>
            <textarea class="noresize" name="goodPoint" id="goodPoint">{{ review.goodPoint }}</textarea>
            <br>
            <br>
            <p class="h5" style="text-align: left; font-family: 'yg-jalnan';">단점</p>
            <textarea class="noresize" name="weakPoint" id="weakPoint">{{ review.weakPoint }}</textarea>
            <br>
            <br>
        </div>
    </div>
    <div class="product_detail col container">
        <div class="product_detail row" style="text-align: left; display: grid; grid-template-rows: 1fr 1.5fr;">
            <p class="h5" style="text-align: left; font-family: 'yg-jalnan';">태그 목록 (공백 문자로 구분됩니다.)</p>
            <textarea class="tag" name="rawTagString" id="rawTagString">{{ review.rawTagString }}</textarea>
            <br><br>
            <button type="submit" class="modify-btn" style="font-family:'NanumSquareRound'; font-size: 19px;">수정 완료</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mainApp/templates/userRecommendation.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>비슷한 유저 추천</title>
<!-- 코사인 유사도를 이용한 사용자 기반 협업 필터링 -->
{% endblock %}

{% block content %}

<!-- 자신과 겹치는 제품 리뷰가 없는 경우 에러메시지 -->
{% if error %}
    <div>에러! 아직 리뷰를 작성하지 않으셨거나, 다른 유저와 같은 제품을 리뷰한 적이 없습니다.</div>
{% else %}
    {% for user in topSimilarity %}
    <div>{{ user }}</div>
    {% endfor %}
{% endif %}

{% endblock %}