LionStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import mainApp.views

import account.urls
import mainApp.urls

urlpatterns = [
    path('', mainApp.views.intro_view, name='introPage'),
    path('admin/', admin.site.urls),
    path('account/', include(account.urls)),
    path('store/', include(mainApp.urls)),
    path('randomLike/', mainApp.views.randomLike, name="randomLike"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path

from . import views

# /account/...
urlpatterns = [
    # 마이 페이지
    path('myPage/', views.myPage_view, name='myPage'),
    path('myPageRedirector/<target>', views.myPageRedirector, name="myPageRedirector"),

    # 로그인 / 로그아웃 / 회원가입 관련
    path('logIn/', views.login_view, name='logIn'),
    path('logOut/', views.logout_view, name='logOut'),
    path('signUp/', views.selectCustomerType_view, name='selectCustomerType'),
    path('signUp/sellerType/', views.selectSellerType_view, name='selectSellerType'),
    path('signUp/user/', views.userSignUp_view, name='userSignUp'),
    path('signUp/webSeller/', views.webSellerSignUp_view, name='webSellerSignUp'),
    path('signUp/stationer/', views.stationerSignUp_view, name='stationerSignUp'),
    path('setLocation/', views.setLocation_view, name="setLocation"),

    # 계정 정보 수정 관련
    path('modifyUserInfo/', views.modifyUserInfo_view, name='modifyUserInfo'),

    # 작성한 웹 판매 정보 목록
    path('webSellInfoList/', views.webSellerInfoList_view, name='webSellInfoList'),
    # 작성한 문구점 판매 정보 목록
    path('stationerSellInfoList/', views.stationerSellInfoList_view, name='stationerSellInfoList'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# 기본 Custom User Model / 일반 리뷰어
class Customer(AbstractUser):
    class Meta:
        verbose_name = "유저"

    is_Customer = models.BooleanField('customer status', default=False)
    is_WebSeller = models.BooleanField('webSeller status', default=False)
    is_Stationer = models.BooleanField('stationer status', default=False)

    # 닉네임(또는 상호명)
    nickname = models.CharField(max_length=15, blank=False, null=False, verbose_name="닉네임/상호명")
    
    # 사용자 대표 이미지
    # 빈 값으로 form에 입력될 경우 기본 이미지로 대체되어야 함
    image = models.ImageField(upload_to="account/profile_image", default="account/profile_image/user_default_image.png", blank=True, null=True, verbose_name="대표 이미지")

    # 소개글
    introduce = models.TextField(verbose_name="소개글", default="", blank=True, null=False)

    # 연락처
    telephone = models.CharField(max_length=20, blank=False, null=True, default="", verbose_name="판매자 연락처")

    # 웹페이지 메인 주소
    link = models.CharField(max_length=200, blank=False, null=True, default="", verbose_name="웹 쇼핑몰 메인 주소")

    # 문방구/리뷰어 위치 위도
    latitude = models.DecimalField(max_digits=10, decimal_places=6, default=0, verbose_name="문방구/리뷰어 위치 위도")
    # 문방구/리뷰어 위치 경도
    longitude = models.DecimalField(max_digits=10, decimal_places=6, default=0, verbose_name="문방구/리뷰어 위치 경도")

    AGE = (
        ("etcs", "기타"),
        ("10s", "10대"),
        ("20s", "20대"),
        ("30s", "30대"),
    )
    age = models.CharField(max_length=5, default=("etcs", "기타"), blank=False, null=True, choices=AGE, verbose_name="연령대")

    JOB = (
        ("J0", "기타"),
        ("J1", "학생"),
        ("J2", "아티스트"),
        ("J3", "자영업"),
        ("J4", "무직"),
    )
    job = models.CharField(max_length=10, default=("J0", "기타"), blank=False, null=True, choices=JOB, verbose_name="직업")


    USAGE = (
        ("U0", "기타"),
        ("U1", "공부/필기"),
        ("U2", "문서 작성"),
        ("U3", "드로잉"),
        ("U4", "다이어리 꾸미기"),
        ("U5", "캘리그라피"),
    )
    usage = models.CharField(max_length=20, default=("U0", "기타"), blank=False, null=True, choices=USAGE, verbose_name="주 사용 용도")

    PEN = (
        ("P0", "기타"),
        ("P1", "볼펜"),
        ("P2", "연필"),
        ("P3", "색연필"),
        ("P4", "만년필"),
        ("P5", "샤프펜슬"),
        ("P6", "형광펜"),
        ("P7", "유성펜"),
        ("P8", "젤펜"),
    )
    penInterest_1 = models.CharField(max_length=10, blank=False, null=True, choices=PEN, default=("P0", "기타"), verbose_name="관심 펜 1순위")
    penInterest_2 = models.CharField(max_length=10, blank=False, null=True, choices=PEN, default=("P0", "기타"), verbose_name="관심 펜 2순위")
    penInterest_3 = models.CharField(max_length=10, blank=False, null=True, choices=PEN, default=("P0", "기타"), verbose_name="관심 펜 3순위")
    

    # 유저 태그(추가)
    tags = models.ManyToManyField('account.CustomerTag', blank=True, verbose_name="유저 설명 태그")

    # 유저 태그 Raw-String Data
    # : 모든 태그들이 띄어쓰기로 구분되어 문자열로 저장되는 필드
    rawTagString = models.TextField(null=True, blank=True, default="", verbose_name="유저 태그 목록 원본 데이터")

    def __str__(self):
        if self.is_Customer:
            typeMarker = "[C]"
        elif self.is_WebSeller:
            typeMarker = "[W]"
        elif self.is_Stationer:
            typeMarker = "[S]"
        else:
            typeMarker = "[UNKNOWN]"
        
        return f"{typeMarker} {self.username}"
    
    job_dict = {p[0]:p[1] for p in JOB}
    for p in JOB:
        job_dict[p] = p[1]

    usage_dict = {p[0]:p[1] for p in USAGE}
    for p in USAGE:
        usage_dict[str(p)] = p[1]

    age_dict = {p[0]:p[1] for p in AGE}
    for p in AGE:
        age_dict[str(p)] = p[1]

    pen_dict = {p[0]:p[1] for p in PEN}
    for p in PEN:
        pen_dict[str(p)] = p[1]

    def getTooltipMessage(self):
        # tuple
        if str(self.job).startswith('('):
            job = str(self.job)[1:-1].split(', ')[0][1:-1]
            usage = str(self.usage)[1:-1].split(', ')[0][1:-1]
            age = str(self.age)[1:-1].split(', ')[0][1:-1]
        else:
            job = self.job
            usage = self.usage
            age = self.age

        user_job = self.job_dict[job] if self.job_dict[job] != "기타" else ""
        user_usage = self.usage_dict[usage] if self.usage_dict[usage] != "기타" else ""
        user_age = self.age_dict[age] if self.age_dict[age] != "기타" else ""

        infos = list(filter(lambda x: x != "", [user_age, user_job, user_usage]))

        return ' | '.join(infos) if len(infos) > 0 else "모든 데이터가 비공개 상태입니다."


class CustomerTag(models.Model):
    class Meta:
        verbose_name = "유저 태그"

    targetCustomer = models.ManyToManyField(Customer)
    tagBody = models.CharField(max_length=10)

    def __str__(self):
        return self.tagBody

    # def __eq__(self, other:str):
    #     return self.tagBody == other

    # def __ne__(self, other:str):
    #     return self.tagBody != other

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout

from .forms import *

from account.models import Customer, CustomerTag
from mainApp.models import *


def selectCustomerType_view(request):
    return render(request, 'selectCustomerType.html')


def connectTagToUser(user:Customer, rawString:str):
    if rawString == "":
        return
    # 일반 str문자열 : 띄어쓰기를 기준으로 태그 정보가 나누어져 있음
    rawTags = rawString.split(' ')
    # 현재 존재하는 태그의 목록
    existTags = CustomerTag.objects.all()
    
    # 새로 만들어질 태그가 이미 존재한다면 새로 생성하지 않는다.
    for newTagName in rawTags:
        if len(newTagName) > 10 : continue

        alreadyExists = False
        for existTag in existTags:
            if existTag.tagBody == newTagName:
                alreadyExists = True
                break
        
        if not alreadyExists:
            newTag = CustomerTag.objects.create(tagBody=newTagName)
            user.tags.add(newTag)
            newTag.targetCustomer.add(user)
        else:
            existTag = CustomerTag.objects.get(tagBody=newTagName)
            user.tags.add(existTag)


def modifyUserTag(user:Customer, before:str):
    newRawTagString = user.rawTagString
    newTagNames = set(newRawTagString.split(' '))
    if newRawTagString =="":
        tags = user.tags.all()
        for tag in tags:
            tag.targetCustomer.remove(user)
        user.tags.clear()
        return

    beforeRawTagString = before

    tagNames_toRemove = set(beforeRawTagString.split(' ')) - newTagNames
    tagNames_toAdd = newTagNames -set(beforeRawTagString.split(' '))

    for name in tagNames_toRemove:
        targetTags = CustomerTag.objects.filter(tagBody=name)
        for tag in targetTags:
            tag.targetCustomer.remove(user)
            user.tags.remove(tag)

            tag.save()
            user.save()
            
            if len(tag.targetCustomer.all()) == 0:
                tag.delete()
            
    tag_namespace = set(map(lambda x: x.tagBody, CustomerTag.objects.all()))
    for name in tagNames_toAdd:
        if name not in tag_namespace:
            newTag : CustomerTag = CustomerTag.objects.create(tagBody=name)
            newTag.targetCustomer.add(user)
            newTag.save()
            user.tags.add(newTag)
            user.save()
        else:
            existTag : CustomerTag = CustomerTag.objects.get(tagBody=name)
            existTag.targetCustomer.add(user)
            existTag.save()
            user.tags.add(existTag)
            user.save()
    
    user.save()
    

def userSignUp_view(request):
    if request.method == 'POST':
        form = UserSignUpForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()
            user.save()
            connectTagToUser(user, form.cleaned_data['rawTagString'])

            login(request, user)
            return redirect("setLocation")
        
        return render(request, 'userSignUp.html', {'form':form})


    else :
        form = UserSignUpForm()
        return render(request, 'userSignUp.html', {'form':form})


def webSellerSignUp_view(request):
    if request.method == 'POST':
        form = WebSellerSignUpForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()
            user.save()
            connectTagToUser(user, form.cleaned_data['rawTagString'])

            login(request, user)
            return redirect("mainPage")
        
        return render(request, 'webSellerSignUp.html', {'form':form})

    else :
        form = WebSellerSignUpForm()
        return render(request, 'webSellerSignUp.html', {'form':form})


def stationerSignUp_view(request):
    if request.method == 'POST':
        form = StationerSignUpForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()
            user.save()
            connectTagToUser(user, form.cleaned_data['rawTagString'])

            login(request, user)
            return redirect("setLocation")
        
        return render(request, 'stationerSignUp.html', {'form':form})

    else :
        form = StationerSignUpForm()
        return render(request, 'stationerSignUp.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request=request, username=username, password=password)

            if user is not None :
                login(request, user)
                return redirect("mainPage")

            return render(request, 'logIn.html', {'form':form})
            

    else :
        form = UserLoginForm()
        return render(request, 'logIn.html', {'form':form})


def logout_view(request):
    logout(request)
    return redirect("mainPage")


@login_required(login_url='/account/logIn/')
def modifyUserInfo_view(request):
    if request.method == "POST":
        beforeString = request.user.rawTagString
        if request.user.is_Customer:
            form = UserModifyForm(request.POST, request.FILES, instance=request.user)
        elif request.user.is_Stationer:
            form = StationerModifyForm(request.POST, request.FILES, instance=request.user)
        elif request.user.is_WebSeller:
            form = WebSellerModifyForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()

            modifyUserTag(request.user, beforeString)

            return redirect('myPage')

    else:
        content = dict()
        print(request.user.is_WebSeller)
        if request.user.is_Customer:
            form = UserModifyForm(instance=request.user)
        elif request.user.is_Stationer:
            form = StationerModifyForm(instance=request.user)
        elif request.user.is_WebSeller:
            form = WebSellerModifyForm(instance=request.user)

        content['form'] = form

        return render(request, 'modifyUserInfo.html', content)


@login_required(login_url='/account/logIn/')
def myPage_view(request):
    content = dict()
    
    user : Customer = request.user

    # 좋아요를 누른 리뷰 목록
    reviewList = PenReview.objects.all()
    likeReviewList = list()
    for review in reviewList:
        if user in review.likers.all():
            likeReviewList.append(review)
    content['likeReviewList'] = likeReviewList
    content['hasNoLikeReviewList'] = (len(likeReviewList) == 0)

    # 좋아요를 누른 제품 목록
    productList = Product.objects.all()
    likeProductList = list()
    for product in productList:
        if user in product.likers.all():
            likeProductList.append(product)
    content['likeProductList'] = likeProductList
    content['hasNoLikeProductList'] = (len(likeProductList) == 0)

    # 작성한 리뷰 목록
    myReviews = PenReview.objects.filter(author=user)
    content['myReviews'] = myReviews
    content['hasMyReviews'] = (len(myReviews) == 0)

    # 웹 판매정보 목록
    if user.is_WebSeller:
        webSellInfoList = WebSellInfo.objects.filter(seller=user)
    else:
        webSellInfoList = []
    content['webSellInfoList'] = webSellInfoList
    content['hasNoWebSellInfoList'] = (len(webSellInfoList) == 0)

    # 문구점 판매정보 목록
    if user.is_Stationer:
        stationerSellInfoList = StationerSellInfo.objects.filter(seller=user)
    else:
        stationerSellInfoList = []
    content['stationerSellInfoList'] = stationerSellInfoList
    content['hasNoStationerSellInfoList'] = (len(stationerSellInfoList) == 0)

    return render(request, 'myPage.html', content)


@login_required(login_url='/account/logIn/')
def myPageRedirector(request, target):
    return redirect(f"/account/myPage#{target}")


def selectSellerType_view(request):
    return render(request, 'selectSellerType.html')


@login_required(login_url='/account/logIn/')
def setLocation_view(request):
    if request.method == "POST":
        try :
            coordinateTuple = eval(request.POST["rawLocation"])
            request.user.latitude = coordinateTuple[0]
            request.user.longitude = coordinateTuple[1]
            request.user.save()
            return redirect("mainPage")

        except:
            return render(request, 'setLocation.html', {'ERROR':True})

    return render(request, 'setLocation.html', {'ERROR':False})


def stationerSellInfoList_view(request):
    return render(request, 'stationerSellInfoList.html')


def webSellerInfoList_view(request):
    return render(request, 'webSellerInfoList.html')

account/templates/accountMain.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>계정 정보 메인 페이지</title>
{% endblock %}

{% block content %}



{% endblock %}

account/templates/logIn.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>로그인 페이지</title>
<style>
    article {
        text-align: center;
        margin: 10rem auto;
    }
    #id_username, #id_password {
        width: 10%;
    }
</style>
{% endblock %}

{% block content %}

<article>
    <form method="POST" class="checkout__form">
        {% csrf_token %}
        <div class="checkout__form__input">
            <p>ID</p>
            {{ form.username }}
        </div>
        <div class="checkout__form__input">
            <p>PW</p>
            {{ form.password }}
        </div>
        <input onclick="play()" class="btn btn-warning" type="submit" value="어흥!" style="color: white; padding: 0.5px 2.5px;">
    </form>
    <audio id='audio_play' src="{% static 'sounds/catSound.wav' %}"></audio> 
</article>

<script type="text/javascript"> 
function play() { 
    var audio = document.getElementById('audio_play'); 
    if (audio.paused) { 
        audio.play(); 
    }else{ 
        audio.pause(); 
        audio.currentTime = 0 
    } 
} 
</script>


{% endblock %}

account/templates/logInPage.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>로그인 페이지</title>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
</form>

{% endblock %}

account/templates/modifyUserInfo.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>개인 정보 수정</title>
<style>
    article {
        padding: 2rem;
    }
    textarea {
        resize: none;
    }
    #id_telephone, #id_link {
        width: 10%;
    }
</style>
{% endblock %}

{% block content %}
<article>
    <form method="POST" enctype="multipart/form-data" class="checkout__form" style="text-align: center;">
        {% csrf_token %}
        <p style=" color: gray; font-size: 8x;">자기소개</p>
        {{ form.introduce }}
        <br>
        <br>
    
        <div>
            <p style="margin-bottom: 0;">PROFILE IMAGE</p>
            <input type="file" name="image" accept="image/*" id="id_image">
        </div>
        <br>
        <br>
    
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
            <div>
                <div>AGE</div>
                {{ form.age }}
            </div>
        
            <div>
                <div>JOB</div>
                {{ form.job }}
            </div>
        
            <div>
                <div>USAGE</div>
                {{ form.usage }}
            </div>
        </div>
    
        <br>
    
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
            <div>
                <div>PEN 1</div>
                {{form.penInterest_1}}
            </div>
            <div>
                <div>PEN 2</div>
                {{form.penInterest_2}}
            </div>
            <div>
                <div>PEN 3</div>
                {{form.penInterest_3}}
            </div>
        </div>
        <br><br>
    
        <div class="checkout__form__input">
            <p>TAG <span style="color: gray;">관심있는 키워드 해쉬태그를 지정하세요 (공백문자로 구분해 입력)</span></p>
        </div>
        {{ form.rawTagString }}
        <br>
        <br>

        {% if user.is_Stationer %}
        <div class="checkout__form__input">
            <p>TEL<span>*</span></p>
            {{ form.telephone }}
        </div>
        <br>    
        {% endif %}

        {% if user.is_WebSeller %}
        <div class="checkout__form__input">
            <p>TEL<span>*</span></p>
            {{ form.telephone }}
        </div>
        <br>
    
        <div class="checkout__form__input">
            <p>WEB/MOBBILE LINK<span>*</span></p>
            {{ form.link }}
        </div>
        <br>    
        {% endif %}
        
        <input type="submit" class="site-btn" value="수정 완료">
    </form>
</article>
{% endblock %}

account/templates/stationerSignUp.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>문방구 사장님 회원가입 페이지</title>
<link rel="stylesheet" href="{% static 'css/signUp.css' %}">
{% endblock %}

{% block content %}
<br>
<h3 style="text-align: center; padding: 1em 3rem 0 3rem; font-family: 'yg-jalnan'; color:#663e27;">
    A. 안녕하세요, 오프라인 판매자님! 회원가입 정보를 기입해주세요.</h3><br><br>

 <!-- 아이디 기입 관련 -->

 <form method="POST" enctype="multipart/form-data" class="checkout__form" style="text-align: center;">
    {% csrf_token %}
    <div class="checkout__form__input">
        <p>ID <span>*</span> </p>
        {{ form.username }}
    </div>
    <span style="color: gray; font-size: 13px;">*ID는 150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.</span>
<br><br><br>

    <!-- 패스워드 기입 관련 -->

    <div class="checkout__form__input">
        <p>Password <span>*</span></p>
        {{ form.password1 }}
    </div>
    <div class="checkout__form__input">
        <p>Again <span>*</span></p>
        {{ form.password2 }}
    </div>
    <div id="password_guide">
        <p style="font-size: 8x;">*비밀번호는 최소 8자 이상이어야 합니다.</p>
        <p style="font-size: 8x;">숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</p>
    </div>
    <br><br>

      <!-- 패스워드 기입 관련 끝-->

    <div class="checkout__form__input">
        <p>E-MAIL <span>*</span></p>
        {{ form.email }}
    </div>
    <br>

    <div class="checkout__form__input">
        <p>NICKNAME <span>*</span></p>
        {{ form.nickname }}
    </div>
    <br>

    <p style=" color: gray; font-size: 8x;">간단한 자기소개를 남겨주세요 !</p>
    {{ form.introduce }}
    <br>

    <div>
        <p>PROFILE IMAGE</p>
        <input type="file" name="image" accept="image/*" id="id_image">
    </div>
    <br>

    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
        <div>
            <div>AGE</div>
            {{ form.age }}
        </div>
    
        <div>
            <div>JOB</div>
            {{ form.job }}
        </div>
    
        <div>
            <div>USAGE</div>
            {{ form.usage }}
        </div>
    </div>

    <br>

    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
        <div>
            <div>PEN 1</div>
            {{form.penInterest_1}}
        </div>
        <div>
            <div>PEN 2</div>
            {{form.penInterest_2}}
        </div>
        <div>
            <div>PEN 3</div>
            {{form.penInterest_3}}
        </div>
    </div>
    <br><br> <br> <br>

    <div class="checkout__form__input">
        <p>TAG <span style="color: gray;">관심있는 키워드 해쉬태그를 지정하세요 (공백문자로 구분해 입력)</span></p>
    </div>
    {{ form.rawTagString }}
    <br>


    <div class="checkout__form__input">
        <p>TEL<span>*</span></p>
        {{ form.telephone }}
    </div>
    <br>

    <input type="submit" class="site-btn" value="다음 단계로">
</form>
{% endblock %}

account/templates/userSignUp.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>일반 리뷰어 회원가입 페이지</title>
<link rel="stylesheet" href="{% static 'css/signUp.css' %}">
<style>
    .filebox label {
        display: inline-block;
        padding: .5em .75em;
        color: #999;
        font-size: inherit;
        line-height: normal;
        vertical-align: middle;
        background-color: #fdfdfd;
        cursor: pointer;
        border: 1px solid #ebebeb;
        border-bottom-color: #e2e2e2;
        border-radius: .25em;
    }

    .filebox input[type="file"] {
        /* 파일 필드 숨기기 */
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        border: 0;
    }
</style>
{% endblock %}

{% block content %}
<h3 style="text-align: center; padding: 1em 3rem 0 3rem; font-family: 'yg-jalnan'; color:#663e27;">
    A. 안녕하세요,리뷰어님! 회원가입 정보를 기입해주세요.</h3><br><br>

<!-- 아이디 기입 관련 -->

<form method="POST" enctype="multipart/form-data" class="checkout__form" style="text-align: center;">
    {% csrf_token %}
    <div class="checkout__form__input">
        <p>ID <span>*</span> </p>
        {{ form.username }}
    </div>
    <span style="color: gray; font-size: 13px;">*ID는 150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.</span>
    <br><br><br>

    <!-- 패스워드 기입 관련 -->

    <div class="checkout__form__input">
        <p>Password <span>*</span></p>
        {{ form.password1 }}
    </div>
    <div class="checkout__form__input">
        <p>Again <span>*</span></p>
        {{ form.password2 }}
    </div>
    <div id="password_guide">
        <p style="font-size: 8x;">*비밀번호는 최소 8자 이상이어야 합니다.</p>
        <p style="font-size: 8x;">숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</p>
    </div>
    <br><br>

    <!-- 패스워드 기입 관련 끝-->

    <div class="checkout__form__input">
        <p>E-MAIL <span>*</span></p>
        {{ form.email }}
    </div>
    <br>

    <div class="checkout__form__input">
        <p>NICKNAME <span>*</span></p>
        {{ form.nickname }}
    </div>
    <br>

    <p style=" color: gray; font-size: 8x;">간단한 자기소개를 남겨주세요 !</p>
    {{ form.introduce }}
    <br>

    <div>
        <p>PROFILE IMAGE</p>
        <!-- <input type="file" name="image" accept="image/*" id="id_image"> -->
        <div class="filebox">
            <label for="fileUpload">업로드</label>
            <input type="file" id="fileUpload" name="image" accept="image/*" id="id_image">
        </div>
    </div>
    <br>

    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
        <div>
            <div>AGE</div>
            {{ form.age }}
        </div>

        <div>
            <div>JOB</div>
            {{ form.job }}
        </div>

        <div>
            <div>USAGE</div>
            {{ form.usage }}
        </div>
    </div>

    <br>

    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; width: 50%; margin-left: 450px;">
        <div>
            <div>PEN 1</div>
            {{form.penInterest_1}}
        </div>
        <div>
            <div>PEN 2</div>
            {{form.penInterest_2}}
        </div>
        <div>
            <div>PEN 3</div>
            {{form.penInterest_3}}
        </div>
    </div>
    <br><br> <br> <br>

    <div class="checkout__form__input">
        <p>TAG <span style="color: gray;">관심있는 키워드 해쉬태그를 지정하세요 (공백문자로 구분해 입력)</span></p>
    </div>
    {{ form.rawTagString }}
    <br>

    <input type="submit" class="site-btn" value="다음 단계로">
</form>
<br><br> <br> <br>

<script>
    $(document).ready(function () {
        var fileTarget = $('.filebox .upload-hidden');
        fileTarget.on('change', function () { // 값이 변경되면
            if (window.FileReader) { // modern browser
                var filename = $(this)[0].files[0].name;
            } else { // old IE
                var filename = $(this).val().split('/').pop().split('\\').pop(); // 파일명만 추출
            }
            // 추출한 파일명 삽입
            $(this).siblings('.upload-name').val(filename);
        });
    });
</script>

{% endblock %}